name: dapresent
description: a flutter library for presenting data
version: 0.0.2
repository: https://github.com/nomagicisreal/dapresent

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.1.1
  damath: ^0.0.21
  datter: ^0.0.18
  dastore: ^0.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true