name: dapresent
description: a flutter library for presenting data
version: 0.0.2
repository: https://github.com/nomagicisreal/dapresent

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

  dastore: ^0.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.1.0
  test: ^1.24.0
